Server redis queue
LyticaMx/vico-analytics-server pull request #2
Opened 2022-03-03 22:53 UTC by Lytica-Carlos

2022-03-04 16:52 UTC, MarioHdpz requested changes

2022-03-04 16:52 UTC, MarioHdpz commented on pyproject.toml
>  python-dotenv = "^0.19.2"
Esta dependencia no tendría que ir en producción, la intención de los .env es usarse sólo en desarrollo.

En producción sólo deben usarse las variables de ambiente de la máquina en la que se deploya.

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +class ConsumeAPI():
Aquí sugeriría cambiar el nombre de la clase.

Como lo indicas en el comentario: """Class to consume an API and queue requests"""

Esta clase no sólo consume el api, lo importante es que encola los requests.

Yo le pronfría algo así como RequestQueuer()

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +    load_dotenv(find_dotenv())
Lo mismo que arriba, el .env no debe leerse en producción. Además ¿por qué está adentro de la clase? Las variables de ambiente deben cargarse de manera general para todo el código, no sólo cuando se instancia una clase.

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +    logging.basicConfig(filename='myapp.log', level=logging.INFO)
Mismo caso, el logger debe ser algo general de tu aplicación, no estar asociado a una clase.

Además, ¿por qué se llama 'myapp'? Suena a que ese código se copio de otro lado sin entenderse.

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +    redis_conn = redis.Redis(
¿Sólo esta clase se va a conectar a Redis?

Si sí está bien que se asigne como una propiedad de la clase, si no yo sugeriría ponerla afuera.

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +        data["visitor"] = (None, data["visitor"])
De nuevo lo del visitor, esto debería ser genérico

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +                requests.exceptions.RequestException,):
Si alguien hace una petición incorrecta esto se estará encolando infinitamente

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +            payload_str = payload[:-2]
¿Por qué este -2?

Sería bueno que le pusieras un comentario de por qué lo haces

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +                payload = pickle.load(handle)
Esto trae una lista, el nombre de la variable debería ser en plural: payloads

2022-03-04 16:52 UTC, MarioHdpz commented on wsgi.py
> +@uwsgidecorators.timer(7200)
Esto quedamos que va a ser manual, no hay que meterlo en un timer.

Hay que hacer un comando para hacerlo manual.

2022-03-04 16:52 UTC, MarioHdpz commented on wsgi.py
> +    app.run(host="0.0.0.0", port=5000)
Falta una línea al final de tu código. Siempre se recomienda dejar una línea al final, hay aplicaciones que dependen de esa línea para saber que ahí acaba el archivo.

2022-03-04 16:52 UTC, MarioHdpz commented on wsgi.py
> +from src.apis.acquisition_api import ConsumeAPI
¿Por qué el archivo se llama acquisition_api? Recuerda que esto debe ser genérico.

2022-03-04 16:52 UTC, MarioHdpz commented on src/apis/acquisition_api.py
> +            os.remove("request.pickle")
¿Qué sucede si eliminas el archivo y luego los requests no funcionan porque no hay internet? ¿Se vuelve a crear?

2022-03-08 22:59 UTC, Lytica-Carlos commented on pyproject.toml
>  python-dotenv = "^0.19.2"
Ya se elimino está dependencia

2022-03-08 23:00 UTC, RobertoAR9 commented on src/apis/acquisition_api.py
> +class ConsumeAPI():
Se renombro la clase a RequestQueuer()

2022-03-08 23:00 UTC, Lytica-Carlos commented on src/apis/acquisition_api.py
> +    load_dotenv(find_dotenv())
Al eliminar la depencia, elimine esta linea

2022-03-08 23:01 UTC, RobertoAR9 commented on src/apis/acquisition_api.py
> +    logging.basicConfig(filename='myapp.log', level=logging.INFO)
El logger se puso fuera de la clase y al archivo .log se le nombro RequestQueuer.log

2022-03-08 23:03 UTC, Lytica-Carlos commented on src/apis/acquisition_api.py
> +    redis_conn = redis.Redis(
Aquí, decidi dejar la conexión de Redis dentro de la clase, porque en la logica que armamos solo está clase se encargaria de encolar las peticiones.

2022-03-08 23:04 UTC, RobertoAR9 commented on wsgi.py
> +@uwsgidecorators.timer(7200)
Se creo un archivo de nombre dump_pickle_file.py para ejecturalo manualmente

2022-03-08 23:04 UTC, Lytica-Carlos commented on wsgi.py
> +from src.apis.acquisition_api import ConsumeAPI
Se cambio el nombre del archivo a request_queue.py

2022-03-08 23:05 UTC, Lytica-Carlos commented on src/apis/acquisition_api.py
> +            os.remove("request.pickle")
Se dejo este eliminado manual

2022-03-10 23:31 UTC, FstRms approved these changes
Se ve bien.

2022-03-10 23:31 UTC, FstRms commented on src/apis/request_queue.py
> +                if self.queue.count < self.queue_size:
Cuidado aquí, no solo los 404 deben dejarse fuera de la cola. El server de acquisition también responde 422 cuando el contenido no es valido y otras API podrían responder distinto también. También habría que revisar bien los casos que levantan el 'requests.exceptions.HTTPError'

2022-03-15 22:32 UTC, merged